# Generated by Django 6.0.1 on 2026-02-04 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='gallery_images',
            field=models.JSONField(blank=True, default=list, help_text='List of image URLs for project gallery'),
        ),
    ]
